
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navber";
import NextAuthProvider from "@/Providers/nextAuthProvider";
import HideOnDashboard from "@/components/HideOnDashboard";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

 
  return (
    <html lang="en">
      <NextAuthProvider>
        <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <HideOnDashboard>
        <Navbar />
      </HideOnDashboard>
        {children}
      </body>
      </NextAuthProvider>
    </html>
  );
}
